### PR TITLE
feat: report issue

### PR DESCRIPTION
**Pull request by KalpeshTalkar**
## Implemented report issue functionality.

While using the app, if you face any issues, you can shake your device or clicking on the `green bug` button on the top right corner of the screen to report issue.
This will present a popup with a snapshot of the current state.

> ## Preview
>

### CODE REVIEW

**Comment by j0nscalet** [comment]
@KalpeshTalkar bunch of errors trying to build this branch

image

**Comment by KalpeshTalkar** [comment]
> @KalpeshTalkar bunch of errors trying to build this branch
> 
> image

@j0nscalet This is due to cocoapod cache issue.
You will have to clear your cocoapods cache and install the latest version of our sdk.
``` Bash
rm -rf ~/Library/Caches/CocoaPods; rm -rf Pods; rm -rf ~/Library/Developer/Xcode/DerivedData/*; pod deintegrate; pod setup; pod install;
```

**Review by j0nscalet — CHANGES_REQUESTED** [review]
@KalpeshTalkar This isn't working. You're missing the `Bearer` label in the `Authorization `header inside the `RoomsAPIService`.

```
func getAllRooms(completion: @escaping  ([RoomInfo]?, APIError?) -> Void) {
        var header = [String: String]()
        header["Authorization"] = "Bearer \(API_KEY)"
```

```
func getRoom(roomID: String, completion: @escaping  (RoomInfo?, APIError?) -> Void) {
        var header = [String: String]()
        header["Authorization"] = "Bearer \(API_KEY)"
```

**Review by j0nscalet — CHANGES_REQUESTED** [review]
@KalpeshTalkar see my comments from PR #6

**Comment by KalpeshTalkar** [comment]
> @KalpeshTalkar This isn't working. You're missing the `Bearer` label in the `Authorization `header inside the `RoomsAPIService`.
> 
> ```
> func getAllRooms(completion: @escaping  ([RoomInfo]?, APIError?) -> Void) {
>         var header = [String: String]()
>         header["Authorization"] = "Bearer \(API_KEY)"
> ```
> 
> ```
> func getRoom(roomID: String, completion: @escaping  (RoomInfo?, APIError?) -> Void) {
>         var header = [String: String]()
>         header["Authorization"] = "Bearer \(API_KEY)"
> ```

@j0nscalet you have to add Bearer as a part of your API key in `info.plist`
api key

**Comment by KalpeshTalkar** [comment]
> @KalpeshTalkar This isn't working. You're missing the `Bearer` label in the `Authorization `header inside the `RoomsAPIService`.
> 
> ```
> func getAllRooms(completion: @escaping  ([RoomInfo]?, APIError?) -> Void) {
>         var header = [String: String]()
>         header["Authorization"] = "Bearer \(API_KEY)"
> ```
> 
> ```
> func getRoom(roomID: String, completion: @escaping  (RoomInfo?, APIError?) -> Void) {
>         var header = [String: String]()
>         header["Authorization"] = "Bearer \(API_KEY)"
> ```

@j0nscalet added `Bearer` in `RoomsAPIService`

**Pull request merged**
